version: '3.8'

services:
  merci-postgres:
    volumes:
      - ../pg_data:/var/lib/postgresql/data/pgdata

  merci-bot:
    environment:
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
    volumes:
      - ../sqlite_data:/merci-bot/sqlite_data

networks:
  wwf_network:
    name: wwf_network
    driver: bridge
    external: false
