version: '3.8'

services:
  merci-postgres:
    stop_grace_period: 1m
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      SLACK_APP_POSTGRES_PASSWORD: ${SLACK_APP_POSTGRES_PASSWORD}
    volumes:
      - /home/wwf/merci_data/postgres:/var/lib/postgresql/data/pgdata

  merci-postgres-backup:
    container_name: merci-postgres-backup
    image: postgres:alpine
    depends_on:
      merci-postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: merci-postgres
      POSTGRES_DB: merci
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MERCI_ENV: ${MERCI_ENV}
    labels:
      logging: "promtail"
      logging_jobname: "merci-postgres-backup"
      logging_env: ${MERCI_ENV:-unknown}
    volumes:
      - /home/wwf/merci_data/postgres_backup:/backup
    command: >
      bash -c "while true; do
        PGPASSWORD=$$POSTGRES_PASSWORD pg_dump -h $$POSTGRES_HOST -U $$POSTGRES_USER -Fc $$POSTGRES_DB > /backup/$$(date +%Y-%m-%d-%H-%M-%S).dump
        echo ""Backup done at $$(date +%Y-%m-%d_%H:%M:%S)""
        ls -1 /backup/*.dump | head -n -10 | xargs rm -f
        sleep 86400
      done"
    networks:
      - wwf_network

  merci-bot:
    build:
      dockerfile: docker/bot/gunicorn.Dockerfile
    environment:
      SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
      SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      SLACK_APP_POSTGRES_PASSWORD: ${SLACK_APP_POSTGRES_PASSWORD}
    volumes:
      - /home/wwf/merci_data/sqlite:/merci-bot/sqlite_data

  merci-webapp:
    build:
      dockerfile: docker/webapp/gunicorn.Dockerfile

  merci-bot-nginx:
    container_name: merci-bot-nginx
    image: merci-bot-nginx
    build:
      context: ..
      dockerfile: docker/nginx/nginx.Dockerfile
    environment:
      MERCI_ENV: ${MERCI_ENV}
    labels:
      logging: "promtail"
      logging_jobname: "merci-bot-nginx"
      logging_env: ${MERCI_ENV:-unknown}
    expose:
      - "80"
    networks:
      - wwf_network
    volumes:
      - "merci_bot_volume:/nginx_sockets"
    depends_on:
      - merci-bot
    restart: always

  merci-pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  merci-pgadmin-nginx:
    container_name: merci-pgadmin-nginx
    image: pgadmin-nginx
    build:
      context: ..
      dockerfile: docker/pgadmin-nginx/pgadmin-nginx.Dockerfile
    # expose:
    #   - "5433"
    environment:
      MERCI_ENV: ${MERCI_ENV}
    labels:
      logging: "promtail"
      logging_jobname: "merci-pgadmin-nginx"
      logging_env: ${MERCI_ENV:-unknown}
    depends_on:
      - merci-pgadmin
    restart: always
    networks:
      - wwf_network

  merci-grafana-promtail:
    container_name: merci-grafana-promtail
    build:
      context: ..
      dockerfile: docker/promtail/promtail.Dockerfile
    environment:
      GRAFANA_COM_API_TOKEN: ${PROD_GRAFANA_COM_API_TOKEN}
      MERCI_ENV: ${MERCI_ENV}
    command: -config.file=/etc/promtail/config.yaml -config.expand-env=true
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      logging: "promtail"
      logging_jobname: "merci-grafana-promtail"
      logging_env: ${MERCI_ENV:-unknown}

  merci-prometheus:
    container_name: merci-prometheus
    depends_on:
      - merci-bot
    build:
      context: ..
      args:
        GRAFANA_COM_API_TOKEN: ${PROD_GRAFANA_COM_API_TOKEN}
      dockerfile: docker/prometheus/prometheus.Dockerfile
    labels:
      logging: "promtail"
      logging_jobname: "merci-prometheus"
      logging_env: ${MERCI_ENV:-unknown}
    restart: always
    networks:
      - wwf_network
