version: '3.8'

services:
  merci-postgres:
    stop_grace_period: 1m
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      SLACK_APP_POSTGRES_PASSWORD: ${SLACK_APP_POSTGRES_PASSWORD}
    volumes:
      - /home/wwf/merci_data/postgres:/var/lib/postgresql/data/pgdata

  merci-postgres-backup:
    container_name: merci-postgres-backup
    image: postgres:alpine
    depends_on:
      merci-postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: merci-postgres
      POSTGRES_DB: merci
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /home/wwf/merci_data/postgres_backup:/backup
    command: >
      bash -c "while true; do
        PGPASSWORD=$$POSTGRES_PASSWORD pg_dump -h $$POSTGRES_HOST -U $$POSTGRES_USER -Fc $$POSTGRES_DB > /backup/$$(date +%Y-%m-%d-%H-%M-%S).dump
        echo ""Backup done at $$(date +%Y-%m-%d_%H:%M:%S)""
        ls -1 /backup/*.dump | head -n -10 | xargs rm -f
        sleep 86400
      done"
    networks:
      - wwf_network

  merci-bot:
    build:
      dockerfile: docker/bot/gunicorn.Dockerfile
    environment:
      SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
      SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      SLACK_APP_POSTGRES_PASSWORD: ${SLACK_APP_POSTGRES_PASSWORD}
    volumes:
      - /home/wwf/merci_data/sqlite:/merci-bot/sqlite_data

  merci-bot-nginx:
    container_name: merci-bot-nginx
    image: merci-bot-nginx
    build:
      context: ..
      dockerfile: docker/nginx/nginx.Dockerfile
    expose:
      - "80"
    networks:
      - wwf_network
    volumes:
      - "merci_bot_volume:/nginx_sockets"
    depends_on:
      - merci-bot
    restart: always

  merci-pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  merci-pgadmin-nginx:
    container_name: merci-pgadmin-nginx
    image: pgadmin-nginx
    build:
      context: ..
      dockerfile: docker/pgadmin-nginx/pgadmin-nginx.Dockerfile
    # expose:
    #   - "5433"
    depends_on:
      - merci-pgadmin
    restart: always
    networks:
      - wwf_network
